model_list:
  - model_name: deepseek-v3
    litellm_params:
      model: openrouter/deepseek/deepseek-chat-v3-0324:free
      api_key: os.environ/OPENROUTER_API_KEY_1

  - model_name: deepseek-r1
    litellm_params:
      model: openrouter/deepseek/deepseek-r1-0528:free
      api_key: os.environ/OPENROUTER_API_KEY_2

  - model_name: o4-mini
    litellm_params:
      model: openai/o4-mini-2025-04-16
      api_key: os.environ/OPENAI_API_KEY

  - model_name: openai-embedding
    litellm_params:
      model: openai/text-embedding-3-small # 1536 dimensions
      api_key: os.environ/OPENAI_API_KEY

  # - model_name: gemini-embedding
  #   litellm_params:
  #     model: gemini/text-embedding-004 # 768 dimensions
  #     api_key: os.environ/GEMINI_API_KEY_1

  # - model_name: gemini-embedding-exp
  #   litellm_params:
  #     model: gemini/gemini-embedding-exp-03-07 # 3072 dimensions
  #     api_key: os.environ/GEMINI_API_KEY_2

  - model_name: gemini-pro
    litellm_params:
      api_key: os.environ/GEMINI_API_KEY_0
      model: gemini/gemini-2.5-pro
      reasoning_effort: "high"

  - model_name: gemini-flash
    litellm_params:
      api_key: os.environ/GEMINI_API_KEY_1
      model: gemini/gemini-2.5-flash

  - model_name: gemini-flash
    litellm_params:
      api_key: os.environ/GEMINI_API_KEY_2
      model: gemini/gemini-2.5-flash

  - model_name: gemini-pro
    litellm_params:
      api_key: os.environ/GEMINI_API_KEY_1
      model: gemini/gemini-2.5-pro
      reasoning_effort: "high"

  - model_name: gemini-pro
    litellm_params:
      api_key: os.environ/GEMINI_API_KEY_2
      model: gemini/gemini-2.5-pro
      reasoning_effort: "high"

litellm_settings:
  num_retries: 1
  fallbacks: [
    {"deepseek-r1":  ["gemini-pro"]},
    {"gemini-flash": ["gemini-pro"]},
    {"*": ["gemini-flash"]}
  ]
  context_window_fallbacks: [
    {"deepseek-r1":  ["gemini-pro"]},
    {"gemini-flash": ["gemini-pro"]},
    {"*": ["gemini-flash"]}
  ]
  allowed_fails: 1
  cooldown_time: 30
  drop_params: true
  stream: false

general_settings:
  log_level: INFO
