model_list:
  - model_name: gemini-home
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY_0
      provider: gemini

  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY_1
      provider: gemini

  - model_name: gemini-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_2
      provider: gemini

  - model_name: deepseek-v3
    litellm_params:
      model: openrouter/deepseek/deepseek-chat-v3-0324:free
      api_key: os.environ/OPENROUTER_API_KEY_1

  - model_name: deepseek-r1
    litellm_params:
      model: openrouter/deepseek/deepseek-r1-0528:free
      api_key: os.environ/OPENROUTER_API_KEY_2

router_settings:
  fallbacks: [
    {"gemini-pro": ["gemini-flash"]},
    {"gemini-flash": ["gemini-home"]},
  ]

general_settings:
  log_level: INFO
