model_list:
  - model_name: deepseek-v3
    litellm_params:
      model: openrouter/deepseek/deepseek-chat-v3-0324:free
      api_key: os.environ/OPENROUTER_API_KEY_1

  - model_name: deepseek-r1
    litellm_params:
      model: openrouter/deepseek/deepseek-r1-0528:free
      api_key: os.environ/OPENROUTER_API_KEY_2

  - model_name: o4-mini
    litellm_params:
      model: openai/o4-mini-2025-04-16
      api_key: os.environ/OPENAI_API_KEY

  - model_name: openai-embedding
    litellm_params:
      model: openai/text-embedding-3-small # 1536 dimensions
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gemini-embedding
    litellm_params:
      model: gemini/text-embedding-004 # 768 dimensions
      api_key: os.environ/GEMINI_API_KEY_0

  - model_name: gemini-home
    litellm_params:
      tpm: 200000
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY_0
      reasoning_effort: "high"

  - model_name: gemini-pro
    litellm_params:
      tpm: 200000
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY_1
      reasoning_effort: "high"
      cooldown: 10
  - model_name: gemini-pro
    litellm_params:
      tpm: 200000
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY_2
      reasoning_effort: "high"
      cooldown: 10

  - model_name: gemini-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_1
  - model_name: gemini-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY_2


router_settings:
  fallbacks: [
    {"gemini-pro":   ["gemini-flash"]},
    {"gemini-flash": ["gemini-home"]},
  ]
  timeout: 10

general_settings:
  log_level: INFO
  num_retries: 0

litellm_settings:
  drop_params: true
